"""Remove start and next task from Task

Revision ID: 6e59f2b68414
Revises: c0b840cc17c8
Create Date: 2025-08-23 02:45:32.713730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e59f2b68414'
down_revision: Union[str, Sequence[str], None] = 'c0b840cc17c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'next_task_no')
    op.drop_column('tasks', 'start_task_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_task_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('next_task_no', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
