"""Update models to match ERD

Revision ID: c0b840cc17c8
Revises: 4bebed130700
Create Date: 2025-08-23 02:40:43.175871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b840cc17c8'
down_revision: Union[str, Sequence[str], None] = '4bebed130700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_rules',
    sa.Column('taskno', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('next_task_no', sa.Integer(), nullable=True),
    sa.Column('tmstamp', sa.DateTime(), nullable=True),
    sa.Column('usrid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['taskno'], ['tasks.taskno'], ),
    sa.PrimaryKeyConstraint('taskno', 'rule')
    )
    op.add_column('cases', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    op.add_column('process_data', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    op.add_column('process_data_types', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    op.add_column('process_definitions', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    op.alter_column('process_definitions', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='is_active::boolean')
    op.add_column('process_types', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    op.add_column('processes', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    op.add_column('status', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    op.add_column('steps', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('tmstamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tmstamp')
    op.drop_column('steps', 'tmstamp')
    op.drop_column('status', 'tmstamp')
    op.drop_column('processes', 'tmstamp')
    op.drop_column('process_types', 'tmstamp')
    op.alter_column('process_definitions', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('process_definitions', 'tmstamp')
    op.drop_column('process_data_types', 'tmstamp')
    op.drop_column('process_data', 'tmstamp')
    op.drop_column('cases', 'tmstamp')
    op.drop_table('task_rules')
    # ### end Alembic commands ###
